version: '3.3'

networks:
  rest:
    driver: bridge

services:
  postgres-rest:
    container_name: postgres-rest
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_DB=hr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    volumes:
      - pgdatarest:/var/lib/postgresql/data
    networks:
      - rest

volumes:
  pgdatarest:
